# Generated by Django 5.1.6 on 2025-02-22 11:07

import django.core.validators
import django.db.models.deletion
import petgoda.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_images/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pettype', models.CharField(choices=[('D', 'หมา'), ('C', 'แมว')], max_length=1)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('allegic', models.CharField(max_length=255, null=True, unique=True)),
                ('properties', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=1000)),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('street_address', models.CharField(max_length=255)),
                ('sub_district', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=5)),
                ('place_id', models.CharField(max_length=1000, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_review', models.PositiveIntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petgoda.location')),
            ],
        ),
        migrations.CreateModel(
            name='FacilitiesHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_veterinary_services', models.BooleanField(default=False)),
                ('has_grooming_services', models.BooleanField(default=False)),
                ('has_training_services', models.BooleanField(default=False)),
                ('has_swimming_pool', models.BooleanField(default=False)),
                ('has_playground', models.BooleanField(default=False)),
                ('has_outdoor_area', models.BooleanField(default=False)),
                ('has_transport_services', models.BooleanField(default=False)),
                ('has_emergency_services', models.BooleanField(default=False)),
                ('has_pet_friendly_cafe', models.BooleanField(default=False)),
                ('has_pet_spa', models.BooleanField(default=False)),
                ('has_special_diet_options', models.BooleanField(default=False)),
                ('has_24h_support', models.BooleanField(default=False)),
                ('has_group_play_sessions', models.BooleanField(default=False)),
                ('has_pet_taxi_service', models.BooleanField(default=False)),
                ('has_pet_fitness_center', models.BooleanField(default=False)),
                ('has_pet_photography', models.BooleanField(default=False)),
                ('has_pet_party_services', models.BooleanField(default=False)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petgoda.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='HotelApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('confirmed', 'ยืนยันแล้ว'), ('cancelled', 'ถูกยกเลิก')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='petgoda.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomname', models.CharField(max_length=30)),
                ('size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating_decimal', models.DecimalField(decimal_places=1, max_digits=3)),
                ('total_review', models.IntegerField(default=0.0)),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('partially_reserved', 'Partially Reserved'), ('fully_reserved', 'Fully Reserved'), ('partially_occupied', 'Partially Occupied'), ('fully_occupied', 'Fully Occupied'), ('maintenance', 'Maintenance'), ('unavailable', 'Unavailable')], default='available', max_length=20)),
                ('max_pets', models.IntegerField(default=1)),
                ('current_pets_count_int', models.IntegerField()),
                ('room_type', models.CharField(max_length=50, null=True)),
                ('allow_pet_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large'), ('all', 'All Sizes')], default='small', max_length=20)),
                ('allow_pet_type', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('all', 'All Pets')], default='dog', max_length=20)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='petgoda.hotel')),
                ('images', models.ManyToManyField(related_name='rooms', to='petgoda.imgroom')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateTimeField(null=True)),
                ('check_out_date', models.DateTimeField(null=True)),
                ('totalprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='unpaid', max_length=20)),
                ('special_request', models.TextField()),
                ('cancellation_reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='petgoda.pet')),
                ('pet_owner', models.ForeignKey(limit_choices_to={'role': 'PETOWNER'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='petgoda.room')),
            ],
        ),
        migrations.CreateModel(
            name='FacilitiesRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_air_conditioning', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('has_webcam_monitoring', models.BooleanField(default=False)),
                ('has_pet_food', models.BooleanField(default=False)),
                ('has_toys', models.BooleanField(default=False)),
                ('has_private_space', models.BooleanField(default=False)),
                ('has_pet_bedding', models.BooleanField(default=False)),
                ('has_soundproofing', models.BooleanField(default=False)),
                ('has_water_dispenser', models.BooleanField(default=False)),
                ('has_emergency_button', models.BooleanField(default=False)),
                ('has_natural_light', models.BooleanField(default=False)),
                ('has_flexible_checkin', models.BooleanField(default=False)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='petgoda.room')),
            ],
        ),
        migrations.CreateModel(
            name='Usersdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('phone_number', models.CharField(max_length=10, null=True, unique=True)),
                ('gender', models.CharField(choices=[('M', 'ผู้ชาย'), ('F', 'ผู้หญิง'), ('LGBTQ', 'LGBTQ+'), ('O', 'อื่นๆ')], max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=petgoda.models.profile_upload_path)),
                ('role', models.CharField(choices=[('Admin', 'ผู้ดูแลระบบ'), ('PetOwner', 'ผู้ใช้ทั่วไป'), ('Hotel', 'โรงแรม')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'ใช้งานอยู่'), ('inactive', 'ไม่ได้ใช้งาน'), ('banned', 'ถูกระงับ')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_district', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('country', models.CharField(blank=True, default='Thailand', max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='petgoda.usersdetail'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('booking_cancellation', 'Booking Cancellation'), ('new_booking_request', 'New Booking Request'), ('promotion', 'Hotel Promotion')], default='booking_confirmation', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='petgoda.usersdetail')),
            ],
        ),
    ]
