# Generated by Django 5.1.6 on 2025-03-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petgoda', '0002_remove_hotel_district_remove_hotel_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersdetail',
            name='status',
        ),
        migrations.AlterField(
            model_name='pet',
            name='allegic',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='properties',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='gender',
            field=models.CharField(choices=[('M', 'ผู้ชาย'), ('F', 'ผู้หญิง'), ('LGBTQ', 'LGBTQ+'), ('O', 'อื่นๆ')], default='O', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='role',
            field=models.CharField(choices=[('Admin', 'ผู้ดูแลระบบ'), ('PetOwner', 'ผู้ใช้ทั่วไป'), ('Hotel', 'โรงแรม')], default='PetOwner', max_length=10),
        ),
    ]
