# Generated by Django 5.1.6 on 2025-03-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petgoda', '0003_remove_usersdetail_status_alter_pet_allegic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'ผู้ชาย'), ('F', 'ผู้หญิง'), ('LGBTQ', 'LGBTQ+'), ('O', 'อื่นๆ')], default='O', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='usersdetail',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
