# Generated by Django 5.1.6 on 2025-03-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petgoda', '0004_alter_usersdetail_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetail',
            name='status',
            field=models.CharField(choices=[('Active', 'ใช้งานได้'), ('Banned', 'ถูกแบน'), ('Pending', 'รอดำเนินการ')], default='Pending', max_length=10),
        ),
    ]
