# Generated by Django 5.1.6 on 2025-03-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petgoda', '0005_usersdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetail',
            name='status',
            field=models.CharField(choices=[('Active', 'ใช้งานได้'), ('Banned', 'ถูกแบน'), ('Pending', 'รอดำเนินการ')], default='Active', max_length=10),
        ),
    ]
