# Generated by Django 5.1.6 on 2025-03-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petgoda', '0005_remove_hotel_location_remove_usersdetail_location_and_more'),
        ('petgoda', '0006_alter_usersdetail_status'),
    ]

    operations = [
    ]
