# Generated by Django 5.1.6 on 2025-03-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petgoda', '0008_alter_pet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imgHotel',
            field=models.ImageField(default='hotel_images/default_hotel.jpg', upload_to='hotel_img/'),
        ),
    ]
